### ISSUE TITLE
Shelly Pro Dimmer 2PM

### ISSUE THREAD

**Issue by justspacedog** [jamesturton/shelly-dimmer-stm32#38]
Hi,

please add support for this device:
https://kb.shelly.cloud/knowledge-base/shelly-pro-dimmer-2pm

Thank you!

**Comment by jamesturton** [comment]
Hi @justspacedog!

Please can you send a photo of how the PCB looks

**Comment by justspacedog** [comment]
![image](https://github.com/jamesturton/shelly-dimmer-stm32/assets/8201551/bca83da4-0f71-43b2-b585-146ec40167e1)
![image](https://github.com/jamesturton/shelly-dimmer-stm32/assets/8201551/abbe5869-7f70-4549-b277-5ec3c744f42f)

Can you work with those?

**Comment by jamesturton** [comment]
Those photos are great, but they don't seem to show the STM chip. Can you see if you can find that on the board somewhere?

**Comment by justspacedog** [comment]
![image](https://github.com/jamesturton/shelly-dimmer-stm32/assets/8201551/16a0f5d7-db64-4f4f-9298-fd0847496091)
![image](https://github.com/jamesturton/shelly-dimmer-stm32/assets/8201551/9738bab3-149e-4bb3-91c0-0e5c71dd2b55)
![image](https://github.com/jamesturton/shelly-dimmer-stm32/assets/8201551/a1c99520-258d-49ec-9c32-36dfd61a4565)

Unfortunately I don’t really know what I’m searching for on the board. 🙈

**Comment by CReimer** [comment]
You won't find a stm32 on this. The first picture clearly shows an ESP32-D0WDQ6
https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf

Unfortunately this means Shelly completely changed their hardware. That's interesting, but out of scope of shelly-dimmer-stm32.

**Comment by jamesturton** [comment]
Then you would be better asking in the Tasmota or ESPHome repo for them to add support their directly.

**Comment by oliv3r** [comment]
> Then you would be better asking in the Tasmota or ESPHome repo for them to add support their directly.

just out of curiosity, while I fully understand and agree that since there is no STM32, things are out of scope, what ARE they using?

I see a 595 shift-register to control the leds and maybe some IO.
Some chip SUPER close to the ESP32, which I can't read the labeling off.
The ade7953acpz is a single phase energy monitoring chip from analog.
U11 probably is the (SPI)PHY.

There seems to be some chips on the relay breakout boards as well, so it could be that that's where the STM32 lies. I would be surprised if they changed that part of their design as well. I get that some companies don't care much about re-use. The switch to ESP32 is probably related to more pins the 8266, desire to do LAN, but to find out a SPI PHY is easier to deal with then the MAC phy (also due to not enough pins maybe), or needing more 'pro' computing then the 8266 offers. But using the same serial protocol with the same stm32 still makes sense I'd reccon.

So @justspacedog could you also add some photo's of those relay boards?
